import Head from "next/head";
import Header from "../Components/Header/Header";
import Nav from "../Components/Nav/Nav";
import Resualt from "../Components/Resualt/Resualt";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <Nav />
      <Resualt />
    </div>
  );
}
