import Head from "next/head";
import Header from "../Components/Header/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <p>Start HULU</p>
    </div>
  );
}
